### ISSUE TITLE
ContinuousCaptureActivity & Fragment Shader(Filter) problem..

### ISSUE THREAD

**Issue by sungtakcho** [google/grafika#26]
Hello,
The developer is developing an app based on the ContinuousCaptureActivity.

ContinuousCaptureActivity filter effects (filter code from CameraCaptureActivity) were added to this exception as follows during filter change occurs.

05-28 01: 26: 18.116: E / AndroidRuntime (1476): java.lang.RuntimeException: glUseProgram: glError 0x501

Is it because you use the SurfaceView? Would you have any solutions?

Thank you.

**Comment by fadden** [comment]
**GL_INVALID_VALUE, 0x0501**
Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.


You'll need to figure out which statement is throwing it and what the problem is. Start by making sure your filter effects are being executed on a thread with a valid EGL context.  The best place to ask about specific issues is http://stackoverflow.com/ .
